[package]
name = "jmend/drakons-legacy"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.1"
Trove = "sleitnick/trove@1.0.1"
Red = "red-blox/red@2.1.0"